export interface FundamentalPricePoint {
  date: string;
  open: number;
  high: number;
  low: number;
  close: number;
  volume?: number | null;
  marketCap?: number | null;
  trailingPe?: number | null;
  forwardPe?: number | null;
  pegRatio?: number | null;
  priceToBook?: number | null;
  priceToSales?: number | null;
  enterpriseToEbitda?: number | null;
  profitMargins?: number | null;
  operatingMargins?: number | null;
  returnOnEquity?: number | null;
  returnOnAssets?: number | null;
  debtToEquity?: number | null;
  currentRatio?: number | null;
  quickRatio?: number | null;
  dividendYield?: number | null;
  freeCashFlow?: number | null;
  circulatingSupply?: number | null;
  totalSupply?: number | null;
  maxSupply?: number | null;
  inflationRate?: number | null;
  fdv?: number | null;
  activeAddresses?: number | null;
  transactionVolume?: number | null;
  transactionCount?: number | null;
  feesGenerated?: number | null;
  tvl?: number | null;
  hashRate?: number | null;
  stakingRatio?: number | null;
  nakamotoCoefficient?: number | null;
  orderBookDepth?: number | null;
  developerActivity?: number | null;
  userGrowth?: number | null;
  revenue?: number | null;
  priceToFeesRatio?: number | null;
  bitcoinDominance?: number | null;
  fearGreedIndex?: number | null;
  inventoryLevels?: number | null;
  costOfProduction?: number | null;
  allInSustainingCost?: number | null;
  reserveReplacementRatio?: number | null;
  contangoBackwardation?: number | null;
  dollarIndexExposure?: number | null;
  inflationCorrelation?: number | null;
  opecSpareCapacity?: number | null;
  chineseDemandIndex?: number | null;
  weatherIndex?: number | null;
}