schema {
  query: Query
}

type Query {
  me: User!
  portfolios(sort: String, limit: Int): [Portfolio!]!
  assetMovers(sort: String, limit: Int): [AssetMover!]!
}

type User {
  id: ID!
  username: String!
  cashBalance: Float!
  lockedBalance: Float!
}

type Portfolio {
  id: ID!
  name: String!
  performance: Float!
  positions: [Position!]!
}

type Position {
  id: ID!
  symbol: String!
  quantity: Float!
  averagePurchasePrice: Float!
  currentPrice: Float
}

type AssetMover {
  symbol: String!
  name: String
  price: Float!
  changePercent: Float!
  changeValue: Float!
  volume: Float!
}