services:
  - type: web
    name: portfolio-manager
    env: docker
    dockerfilePath: ./portfolio-manager/Dockerfile
    dockerContext: .
    plan: free
    region: oregon
    healthCheckPath: /actuator/health/readiness
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: DB_NAME
        value: finsight_db
      - key: DB_USER
        value: user
      - key: DB_PASSWORD
        sync: false
      - key: SPRING_REDIS_URL
        sync: false
      - key: SPRING_REDIS_SSL_ENABLED
        value: "true"
      - key: SPRING_DATA_COLLECTOR_HEALTH_CHECK_ENABLED
        value: "true"
      - key: JWT_SECRET
        sync: false
      - key: JWT_ISSUER
        value: capital-fourge
      - key: JWT_ACCESS_EXPIRATION_MS
        value: "86400000"
      - key: JWT_REFRESH_EXPIRATION_MS
        value: "604800000"
      - key: DATA_COLLECTOR_BASE_URL
        value: https://data-collector.onrender.com

  - type: web
    name: data-collector
    env: docker
    dockerfilePath: ./data-collector/Dockerfile
    dockerContext: ./data-collector
    plan: free
    region: oregon
    healthCheckPath: /health
    envVars:
      - key: RENDER
        value: "true"
      - key: PORT
        value: "8000"