// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: financial_data.proto

package com.finsight.proto;

public interface BatchStockResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:financial.BatchStockResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, double&gt; prices = 1;</code>
   */
  int getPricesCount();
  /**
   * <code>map&lt;string, double&gt; prices = 1;</code>
   */
  boolean containsPrices(
      java.lang.String key);
  /**
   * Use {@link #getPricesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.Double>
  getPrices();
  /**
   * <code>map&lt;string, double&gt; prices = 1;</code>
   */
  java.util.Map<java.lang.String, java.lang.Double>
  getPricesMap();
  /**
   * <code>map&lt;string, double&gt; prices = 1;</code>
   */
  double getPricesOrDefault(
      java.lang.String key,
      double defaultValue);
  /**
   * <code>map&lt;string, double&gt; prices = 1;</code>
   */
  double getPricesOrThrow(
      java.lang.String key);
}
