// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: financial_data.proto

package com.finsight.proto;

/**
 * Protobuf type {@code financial.BatchStockResponse}
 */
public final class BatchStockResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:financial.BatchStockResponse)
    BatchStockResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BatchStockResponse.newBuilder() to construct.
  private BatchStockResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BatchStockResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BatchStockResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.finsight.proto.FinancialDataProto.internal_static_financial_BatchStockResponse_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetPrices();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.finsight.proto.FinancialDataProto.internal_static_financial_BatchStockResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.finsight.proto.BatchStockResponse.class, com.finsight.proto.BatchStockResponse.Builder.class);
  }

  public static final int PRICES_FIELD_NUMBER = 1;
  private static final class PricesDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.Double> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.Double>newDefaultInstance(
                com.finsight.proto.FinancialDataProto.internal_static_financial_BatchStockResponse_PricesEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.DOUBLE,
                0D);
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.Double> prices_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.Double>
  internalGetPrices() {
    if (prices_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          PricesDefaultEntryHolder.defaultEntry);
    }
    return prices_;
  }
  public int getPricesCount() {
    return internalGetPrices().getMap().size();
  }
  /**
   * <code>map&lt;string, double&gt; prices = 1;</code>
   */
  @java.lang.Override
  public boolean containsPrices(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetPrices().getMap().containsKey(key);
  }
  /**
   * Use {@link #getPricesMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.Double> getPrices() {
    return getPricesMap();
  }
  /**
   * <code>map&lt;string, double&gt; prices = 1;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.Double> getPricesMap() {
    return internalGetPrices().getMap();
  }
  /**
   * <code>map&lt;string, double&gt; prices = 1;</code>
   */
  @java.lang.Override
  public double getPricesOrDefault(
      java.lang.String key,
      double defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.Double> map =
        internalGetPrices().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, double&gt; prices = 1;</code>
   */
  @java.lang.Override
  public double getPricesOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.Double> map =
        internalGetPrices().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetPrices(),
        PricesDefaultEntryHolder.defaultEntry,
        1);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, java.lang.Double> entry
         : internalGetPrices().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.Double>
      prices__ = PricesDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, prices__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.finsight.proto.BatchStockResponse)) {
      return super.equals(obj);
    }
    com.finsight.proto.BatchStockResponse other = (com.finsight.proto.BatchStockResponse) obj;

    if (!internalGetPrices().equals(
        other.internalGetPrices())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetPrices().getMap().isEmpty()) {
      hash = (37 * hash) + PRICES_FIELD_NUMBER;
      hash = (53 * hash) + internalGetPrices().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.finsight.proto.BatchStockResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.finsight.proto.BatchStockResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.finsight.proto.BatchStockResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.finsight.proto.BatchStockResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.finsight.proto.BatchStockResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.finsight.proto.BatchStockResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.finsight.proto.BatchStockResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.finsight.proto.BatchStockResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.finsight.proto.BatchStockResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.finsight.proto.BatchStockResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.finsight.proto.BatchStockResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.finsight.proto.BatchStockResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.finsight.proto.BatchStockResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code financial.BatchStockResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:financial.BatchStockResponse)
      com.finsight.proto.BatchStockResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.finsight.proto.FinancialDataProto.internal_static_financial_BatchStockResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetPrices();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutablePrices();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.finsight.proto.FinancialDataProto.internal_static_financial_BatchStockResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.finsight.proto.BatchStockResponse.class, com.finsight.proto.BatchStockResponse.Builder.class);
    }

    // Construct using com.finsight.proto.BatchStockResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      internalGetMutablePrices().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.finsight.proto.FinancialDataProto.internal_static_financial_BatchStockResponse_descriptor;
    }

    @java.lang.Override
    public com.finsight.proto.BatchStockResponse getDefaultInstanceForType() {
      return com.finsight.proto.BatchStockResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.finsight.proto.BatchStockResponse build() {
      com.finsight.proto.BatchStockResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.finsight.proto.BatchStockResponse buildPartial() {
      com.finsight.proto.BatchStockResponse result = new com.finsight.proto.BatchStockResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.finsight.proto.BatchStockResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.prices_ = internalGetPrices();
        result.prices_.makeImmutable();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.finsight.proto.BatchStockResponse) {
        return mergeFrom((com.finsight.proto.BatchStockResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.finsight.proto.BatchStockResponse other) {
      if (other == com.finsight.proto.BatchStockResponse.getDefaultInstance()) return this;
      internalGetMutablePrices().mergeFrom(
          other.internalGetPrices());
      bitField0_ |= 0x00000001;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.Double>
              prices__ = input.readMessage(
                  PricesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutablePrices().getMutableMap().put(
                  prices__.getKey(), prices__.getValue());
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Double> prices_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Double>
        internalGetPrices() {
      if (prices_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            PricesDefaultEntryHolder.defaultEntry);
      }
      return prices_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.Double>
        internalGetMutablePrices() {
      if (prices_ == null) {
        prices_ = com.google.protobuf.MapField.newMapField(
            PricesDefaultEntryHolder.defaultEntry);
      }
      if (!prices_.isMutable()) {
        prices_ = prices_.copy();
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return prices_;
    }
    public int getPricesCount() {
      return internalGetPrices().getMap().size();
    }
    /**
     * <code>map&lt;string, double&gt; prices = 1;</code>
     */
    @java.lang.Override
    public boolean containsPrices(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetPrices().getMap().containsKey(key);
    }
    /**
     * Use {@link #getPricesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Double> getPrices() {
      return getPricesMap();
    }
    /**
     * <code>map&lt;string, double&gt; prices = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.Double> getPricesMap() {
      return internalGetPrices().getMap();
    }
    /**
     * <code>map&lt;string, double&gt; prices = 1;</code>
     */
    @java.lang.Override
    public double getPricesOrDefault(
        java.lang.String key,
        double defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Double> map =
          internalGetPrices().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, double&gt; prices = 1;</code>
     */
    @java.lang.Override
    public double getPricesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Double> map =
          internalGetPrices().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearPrices() {
      bitField0_ = (bitField0_ & ~0x00000001);
      internalGetMutablePrices().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, double&gt; prices = 1;</code>
     */
    public Builder removePrices(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutablePrices().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Double>
        getMutablePrices() {
      bitField0_ |= 0x00000001;
      return internalGetMutablePrices().getMutableMap();
    }
    /**
     * <code>map&lt;string, double&gt; prices = 1;</code>
     */
    public Builder putPrices(
        java.lang.String key,
        double value) {
      if (key == null) { throw new NullPointerException("map key"); }
      
      internalGetMutablePrices().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>map&lt;string, double&gt; prices = 1;</code>
     */
    public Builder putAllPrices(
        java.util.Map<java.lang.String, java.lang.Double> values) {
      internalGetMutablePrices().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000001;
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:financial.BatchStockResponse)
  }

  // @@protoc_insertion_point(class_scope:financial.BatchStockResponse)
  private static final com.finsight.proto.BatchStockResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.finsight.proto.BatchStockResponse();
  }

  public static com.finsight.proto.BatchStockResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BatchStockResponse>
      PARSER = new com.google.protobuf.AbstractParser<BatchStockResponse>() {
    @java.lang.Override
    public BatchStockResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BatchStockResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BatchStockResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.finsight.proto.BatchStockResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

