// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: financial_data.proto

package com.finsight.proto;

public interface CategorizedAssetsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:financial.CategorizedAssetsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .financial.Asset assets = 1;</code>
   */
  java.util.List<com.finsight.proto.Asset> 
      getAssetsList();
  /**
   * <code>repeated .financial.Asset assets = 1;</code>
   */
  com.finsight.proto.Asset getAssets(int index);
  /**
   * <code>repeated .financial.Asset assets = 1;</code>
   */
  int getAssetsCount();
  /**
   * <code>repeated .financial.Asset assets = 1;</code>
   */
  java.util.List<? extends com.finsight.proto.AssetOrBuilder> 
      getAssetsOrBuilderList();
  /**
   * <code>repeated .financial.Asset assets = 1;</code>
   */
  com.finsight.proto.AssetOrBuilder getAssetsOrBuilder(
      int index);
}
