// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: financial_data.proto

package com.finsight.proto;

/**
 * Protobuf type {@code financial.CategorizedAssetsResponse}
 */
public final class CategorizedAssetsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:financial.CategorizedAssetsResponse)
    CategorizedAssetsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CategorizedAssetsResponse.newBuilder() to construct.
  private CategorizedAssetsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CategorizedAssetsResponse() {
    assets_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CategorizedAssetsResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.finsight.proto.FinancialDataProto.internal_static_financial_CategorizedAssetsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.finsight.proto.FinancialDataProto.internal_static_financial_CategorizedAssetsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.finsight.proto.CategorizedAssetsResponse.class, com.finsight.proto.CategorizedAssetsResponse.Builder.class);
  }

  public static final int ASSETS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.finsight.proto.Asset> assets_;
  /**
   * <code>repeated .financial.Asset assets = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.finsight.proto.Asset> getAssetsList() {
    return assets_;
  }
  /**
   * <code>repeated .financial.Asset assets = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.finsight.proto.AssetOrBuilder> 
      getAssetsOrBuilderList() {
    return assets_;
  }
  /**
   * <code>repeated .financial.Asset assets = 1;</code>
   */
  @java.lang.Override
  public int getAssetsCount() {
    return assets_.size();
  }
  /**
   * <code>repeated .financial.Asset assets = 1;</code>
   */
  @java.lang.Override
  public com.finsight.proto.Asset getAssets(int index) {
    return assets_.get(index);
  }
  /**
   * <code>repeated .financial.Asset assets = 1;</code>
   */
  @java.lang.Override
  public com.finsight.proto.AssetOrBuilder getAssetsOrBuilder(
      int index) {
    return assets_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < assets_.size(); i++) {
      output.writeMessage(1, assets_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < assets_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, assets_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.finsight.proto.CategorizedAssetsResponse)) {
      return super.equals(obj);
    }
    com.finsight.proto.CategorizedAssetsResponse other = (com.finsight.proto.CategorizedAssetsResponse) obj;

    if (!getAssetsList()
        .equals(other.getAssetsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAssetsCount() > 0) {
      hash = (37 * hash) + ASSETS_FIELD_NUMBER;
      hash = (53 * hash) + getAssetsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.finsight.proto.CategorizedAssetsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.finsight.proto.CategorizedAssetsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.finsight.proto.CategorizedAssetsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.finsight.proto.CategorizedAssetsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.finsight.proto.CategorizedAssetsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.finsight.proto.CategorizedAssetsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.finsight.proto.CategorizedAssetsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.finsight.proto.CategorizedAssetsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.finsight.proto.CategorizedAssetsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.finsight.proto.CategorizedAssetsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.finsight.proto.CategorizedAssetsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.finsight.proto.CategorizedAssetsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.finsight.proto.CategorizedAssetsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code financial.CategorizedAssetsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:financial.CategorizedAssetsResponse)
      com.finsight.proto.CategorizedAssetsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.finsight.proto.FinancialDataProto.internal_static_financial_CategorizedAssetsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.finsight.proto.FinancialDataProto.internal_static_financial_CategorizedAssetsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.finsight.proto.CategorizedAssetsResponse.class, com.finsight.proto.CategorizedAssetsResponse.Builder.class);
    }

    // Construct using com.finsight.proto.CategorizedAssetsResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (assetsBuilder_ == null) {
        assets_ = java.util.Collections.emptyList();
      } else {
        assets_ = null;
        assetsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.finsight.proto.FinancialDataProto.internal_static_financial_CategorizedAssetsResponse_descriptor;
    }

    @java.lang.Override
    public com.finsight.proto.CategorizedAssetsResponse getDefaultInstanceForType() {
      return com.finsight.proto.CategorizedAssetsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.finsight.proto.CategorizedAssetsResponse build() {
      com.finsight.proto.CategorizedAssetsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.finsight.proto.CategorizedAssetsResponse buildPartial() {
      com.finsight.proto.CategorizedAssetsResponse result = new com.finsight.proto.CategorizedAssetsResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.finsight.proto.CategorizedAssetsResponse result) {
      if (assetsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          assets_ = java.util.Collections.unmodifiableList(assets_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.assets_ = assets_;
      } else {
        result.assets_ = assetsBuilder_.build();
      }
    }

    private void buildPartial0(com.finsight.proto.CategorizedAssetsResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.finsight.proto.CategorizedAssetsResponse) {
        return mergeFrom((com.finsight.proto.CategorizedAssetsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.finsight.proto.CategorizedAssetsResponse other) {
      if (other == com.finsight.proto.CategorizedAssetsResponse.getDefaultInstance()) return this;
      if (assetsBuilder_ == null) {
        if (!other.assets_.isEmpty()) {
          if (assets_.isEmpty()) {
            assets_ = other.assets_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAssetsIsMutable();
            assets_.addAll(other.assets_);
          }
          onChanged();
        }
      } else {
        if (!other.assets_.isEmpty()) {
          if (assetsBuilder_.isEmpty()) {
            assetsBuilder_.dispose();
            assetsBuilder_ = null;
            assets_ = other.assets_;
            bitField0_ = (bitField0_ & ~0x00000001);
            assetsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAssetsFieldBuilder() : null;
          } else {
            assetsBuilder_.addAllMessages(other.assets_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.finsight.proto.Asset m =
                  input.readMessage(
                      com.finsight.proto.Asset.parser(),
                      extensionRegistry);
              if (assetsBuilder_ == null) {
                ensureAssetsIsMutable();
                assets_.add(m);
              } else {
                assetsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.finsight.proto.Asset> assets_ =
      java.util.Collections.emptyList();
    private void ensureAssetsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        assets_ = new java.util.ArrayList<com.finsight.proto.Asset>(assets_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.finsight.proto.Asset, com.finsight.proto.Asset.Builder, com.finsight.proto.AssetOrBuilder> assetsBuilder_;

    /**
     * <code>repeated .financial.Asset assets = 1;</code>
     */
    public java.util.List<com.finsight.proto.Asset> getAssetsList() {
      if (assetsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(assets_);
      } else {
        return assetsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .financial.Asset assets = 1;</code>
     */
    public int getAssetsCount() {
      if (assetsBuilder_ == null) {
        return assets_.size();
      } else {
        return assetsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .financial.Asset assets = 1;</code>
     */
    public com.finsight.proto.Asset getAssets(int index) {
      if (assetsBuilder_ == null) {
        return assets_.get(index);
      } else {
        return assetsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .financial.Asset assets = 1;</code>
     */
    public Builder setAssets(
        int index, com.finsight.proto.Asset value) {
      if (assetsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAssetsIsMutable();
        assets_.set(index, value);
        onChanged();
      } else {
        assetsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .financial.Asset assets = 1;</code>
     */
    public Builder setAssets(
        int index, com.finsight.proto.Asset.Builder builderForValue) {
      if (assetsBuilder_ == null) {
        ensureAssetsIsMutable();
        assets_.set(index, builderForValue.build());
        onChanged();
      } else {
        assetsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .financial.Asset assets = 1;</code>
     */
    public Builder addAssets(com.finsight.proto.Asset value) {
      if (assetsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAssetsIsMutable();
        assets_.add(value);
        onChanged();
      } else {
        assetsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .financial.Asset assets = 1;</code>
     */
    public Builder addAssets(
        int index, com.finsight.proto.Asset value) {
      if (assetsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAssetsIsMutable();
        assets_.add(index, value);
        onChanged();
      } else {
        assetsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .financial.Asset assets = 1;</code>
     */
    public Builder addAssets(
        com.finsight.proto.Asset.Builder builderForValue) {
      if (assetsBuilder_ == null) {
        ensureAssetsIsMutable();
        assets_.add(builderForValue.build());
        onChanged();
      } else {
        assetsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .financial.Asset assets = 1;</code>
     */
    public Builder addAssets(
        int index, com.finsight.proto.Asset.Builder builderForValue) {
      if (assetsBuilder_ == null) {
        ensureAssetsIsMutable();
        assets_.add(index, builderForValue.build());
        onChanged();
      } else {
        assetsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .financial.Asset assets = 1;</code>
     */
    public Builder addAllAssets(
        java.lang.Iterable<? extends com.finsight.proto.Asset> values) {
      if (assetsBuilder_ == null) {
        ensureAssetsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, assets_);
        onChanged();
      } else {
        assetsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .financial.Asset assets = 1;</code>
     */
    public Builder clearAssets() {
      if (assetsBuilder_ == null) {
        assets_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        assetsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .financial.Asset assets = 1;</code>
     */
    public Builder removeAssets(int index) {
      if (assetsBuilder_ == null) {
        ensureAssetsIsMutable();
        assets_.remove(index);
        onChanged();
      } else {
        assetsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .financial.Asset assets = 1;</code>
     */
    public com.finsight.proto.Asset.Builder getAssetsBuilder(
        int index) {
      return getAssetsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .financial.Asset assets = 1;</code>
     */
    public com.finsight.proto.AssetOrBuilder getAssetsOrBuilder(
        int index) {
      if (assetsBuilder_ == null) {
        return assets_.get(index);  } else {
        return assetsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .financial.Asset assets = 1;</code>
     */
    public java.util.List<? extends com.finsight.proto.AssetOrBuilder> 
         getAssetsOrBuilderList() {
      if (assetsBuilder_ != null) {
        return assetsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(assets_);
      }
    }
    /**
     * <code>repeated .financial.Asset assets = 1;</code>
     */
    public com.finsight.proto.Asset.Builder addAssetsBuilder() {
      return getAssetsFieldBuilder().addBuilder(
          com.finsight.proto.Asset.getDefaultInstance());
    }
    /**
     * <code>repeated .financial.Asset assets = 1;</code>
     */
    public com.finsight.proto.Asset.Builder addAssetsBuilder(
        int index) {
      return getAssetsFieldBuilder().addBuilder(
          index, com.finsight.proto.Asset.getDefaultInstance());
    }
    /**
     * <code>repeated .financial.Asset assets = 1;</code>
     */
    public java.util.List<com.finsight.proto.Asset.Builder> 
         getAssetsBuilderList() {
      return getAssetsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.finsight.proto.Asset, com.finsight.proto.Asset.Builder, com.finsight.proto.AssetOrBuilder> 
        getAssetsFieldBuilder() {
      if (assetsBuilder_ == null) {
        assetsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.finsight.proto.Asset, com.finsight.proto.Asset.Builder, com.finsight.proto.AssetOrBuilder>(
                assets_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        assets_ = null;
      }
      return assetsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:financial.CategorizedAssetsResponse)
  }

  // @@protoc_insertion_point(class_scope:financial.CategorizedAssetsResponse)
  private static final com.finsight.proto.CategorizedAssetsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.finsight.proto.CategorizedAssetsResponse();
  }

  public static com.finsight.proto.CategorizedAssetsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CategorizedAssetsResponse>
      PARSER = new com.google.protobuf.AbstractParser<CategorizedAssetsResponse>() {
    @java.lang.Override
    public CategorizedAssetsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CategorizedAssetsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CategorizedAssetsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.finsight.proto.CategorizedAssetsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

