// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: financial_data.proto

package com.finsight.proto;

public interface EmptyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:financial.EmptyRequest)
    com.google.protobuf.MessageOrBuilder {
}
