// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: financial_data.proto

package com.finsight.proto;

public final class FinancialDataProto {
  private FinancialDataProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_financial_Asset_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_financial_Asset_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_financial_CategorizedAssetsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_financial_CategorizedAssetsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_financial_StockRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_financial_StockRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_financial_StockPriceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_financial_StockPriceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_financial_BatchStockRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_financial_BatchStockRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_financial_BatchStockResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_financial_BatchStockResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_financial_BatchStockResponse_PricesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_financial_BatchStockResponse_PricesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_financial_HistoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_financial_HistoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_financial_PricePoint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_financial_PricePoint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_financial_HistoryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_financial_HistoryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_financial_EmptyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_financial_EmptyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_financial_SymbolsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_financial_SymbolsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024financial_data.proto\022\tfinancial\"]\n\005Ass" +
      "et\022\016\n\006symbol\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\020\n\010cate" +
      "gory\030\003 \001(\t\022\023\n\013description\030\004 \001(\t\022\017\n\007websi" +
      "te\030\005 \001(\t\"=\n\031CategorizedAssetsResponse\022 \n" +
      "\006assets\030\001 \003(\0132\020.financial.Asset\"\036\n\014Stock" +
      "Request\022\016\n\006symbol\030\001 \001(\t\"F\n\022StockPriceRes" +
      "ponse\022\016\n\006symbol\030\001 \001(\t\022\r\n\005price\030\002 \001(\001\022\021\n\t" +
      "timestamp\030\003 \001(\t\"$\n\021BatchStockRequest\022\017\n\007" +
      "symbols\030\001 \003(\t\"~\n\022BatchStockResponse\0229\n\006p" +
      "rices\030\001 \003(\0132).financial.BatchStockRespon" +
      "se.PricesEntry\032-\n\013PricesEntry\022\013\n\003key\030\001 \001" +
      "(\t\022\r\n\005value\030\002 \001(\001:\0028\001\".\n\016HistoryRequest\022" +
      "\016\n\006symbol\030\001 \001(\t\022\014\n\004days\030\002 \001(\005\"\332\t\n\nPriceP" +
      "oint\022\014\n\004open\030\001 \001(\001\022\014\n\004high\030\002 \001(\001\022\013\n\003low\030" +
      "\003 \001(\001\022\r\n\005close\030\004 \001(\001\022\016\n\006volume\030\005 \001(\001\022\014\n\004" +
      "date\030\006 \001(\t\022\022\n\nmarket_cap\030\007 \001(\001\022\023\n\013traili" +
      "ng_pe\030\010 \001(\001\022\022\n\nforward_pe\030\t \001(\001\022\021\n\tpeg_r" +
      "atio\030\n \001(\001\022\025\n\rprice_to_book\030\013 \001(\001\022\026\n\016pri" +
      "ce_to_sales\030\014 \001(\001\022\034\n\024enterprise_to_ebitd" +
      "a\030\r \001(\001\022\026\n\016profit_margins\030\016 \001(\001\022\031\n\021opera" +
      "ting_margins\030\017 \001(\001\022\030\n\020return_on_equity\030\020" +
      " \001(\001\022\030\n\020return_on_assets\030\021 \001(\001\022\026\n\016debt_t" +
      "o_equity\030\022 \001(\001\022\025\n\rcurrent_ratio\030\023 \001(\001\022\023\n" +
      "\013quick_ratio\030\024 \001(\001\022\026\n\016dividend_yield\030\025 \001" +
      "(\001\022\026\n\016free_cash_flow\030\026 \001(\001\022\032\n\022circulatin" +
      "g_supply\030\027 \001(\001\022\024\n\014total_supply\030\030 \001(\001\022\022\n\n" +
      "max_supply\030\031 \001(\001\022\026\n\016inflation_rate\030\032 \001(\001" +
      "\022\013\n\003fdv\030\033 \001(\001\022\030\n\020active_addresses\030\034 \001(\001\022" +
      "\032\n\022transaction_volume\030\035 \001(\001\022\031\n\021transacti" +
      "on_count\030\036 \001(\001\022\026\n\016fees_generated\030\037 \001(\001\022\013" +
      "\n\003tvl\030  \001(\001\022\021\n\thash_rate\030! \001(\001\022\025\n\rstakin" +
      "g_ratio\030\" \001(\001\022\034\n\024nakamoto_coefficient\030# " +
      "\001(\001\022\030\n\020order_book_depth\030$ \001(\001\022\032\n\022develop" +
      "er_activity\030% \001(\001\022\023\n\013user_growth\030& \001(\001\022\017" +
      "\n\007revenue\030\' \001(\001\022\033\n\023price_to_fees_ratio\030(" +
      " \001(\001\022\031\n\021bitcoin_dominance\030) \001(\001\022\030\n\020fear_" +
      "greed_index\030* \001(\001\022\030\n\020inventory_levels\030+ " +
      "\001(\001\022\032\n\022cost_of_production\030, \001(\001\022\036\n\026all_i" +
      "n_sustaining_cost\030- \001(\001\022!\n\031reserve_repla" +
      "cement_ratio\030. \001(\001\022\036\n\026contango_backwarda" +
      "tion\030/ \001(\001\022\035\n\025dollar_index_exposure\0300 \001(" +
      "\001\022\035\n\025inflation_correlation\0301 \001(\001\022\033\n\023opec" +
      "_spare_capacity\0302 \001(\001\022\034\n\024chinese_demand_" +
      "index\0303 \001(\001\022\025\n\rweather_index\0304 \001(\001\"I\n\017Hi" +
      "storyResponse\022\016\n\006symbol\030\001 \001(\t\022&\n\007history" +
      "\030\002 \003(\0132\025.financial.PricePoint\"\016\n\014EmptyRe" +
      "quest\"\"\n\017SymbolsResponse\022\017\n\007symbols\030\001 \003(" +
      "\t2\233\003\n\024FinancialDataService\022G\n\rGetStockPr" +
      "ice\022\027.financial.StockRequest\032\035.financial" +
      ".StockPriceResponse\022M\n\016GetBatchPrices\022\034." +
      "financial.BatchStockRequest\032\035.financial." +
      "BatchStockResponse\022H\n\017GetPriceHistory\022\031." +
      "financial.HistoryRequest\032\032.financial.His" +
      "toryResponse\022J\n\023GetAvailableSymbols\022\027.fi" +
      "nancial.EmptyRequest\032\032.financial.Symbols" +
      "Response\022U\n\024GetCategorizedAssets\022\027.finan" +
      "cial.EmptyRequest\032$.financial.Categorize" +
      "dAssetsResponseB*\n\022com.finsight.protoB\022F" +
      "inancialDataProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_financial_Asset_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_financial_Asset_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_financial_Asset_descriptor,
        new java.lang.String[] { "Symbol", "Name", "Category", "Description", "Website", });
    internal_static_financial_CategorizedAssetsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_financial_CategorizedAssetsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_financial_CategorizedAssetsResponse_descriptor,
        new java.lang.String[] { "Assets", });
    internal_static_financial_StockRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_financial_StockRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_financial_StockRequest_descriptor,
        new java.lang.String[] { "Symbol", });
    internal_static_financial_StockPriceResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_financial_StockPriceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_financial_StockPriceResponse_descriptor,
        new java.lang.String[] { "Symbol", "Price", "Timestamp", });
    internal_static_financial_BatchStockRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_financial_BatchStockRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_financial_BatchStockRequest_descriptor,
        new java.lang.String[] { "Symbols", });
    internal_static_financial_BatchStockResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_financial_BatchStockResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_financial_BatchStockResponse_descriptor,
        new java.lang.String[] { "Prices", });
    internal_static_financial_BatchStockResponse_PricesEntry_descriptor =
      internal_static_financial_BatchStockResponse_descriptor.getNestedTypes().get(0);
    internal_static_financial_BatchStockResponse_PricesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_financial_BatchStockResponse_PricesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_financial_HistoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_financial_HistoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_financial_HistoryRequest_descriptor,
        new java.lang.String[] { "Symbol", "Days", });
    internal_static_financial_PricePoint_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_financial_PricePoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_financial_PricePoint_descriptor,
        new java.lang.String[] { "Open", "High", "Low", "Close", "Volume", "Date", "MarketCap", "TrailingPe", "ForwardPe", "PegRatio", "PriceToBook", "PriceToSales", "EnterpriseToEbitda", "ProfitMargins", "OperatingMargins", "ReturnOnEquity", "ReturnOnAssets", "DebtToEquity", "CurrentRatio", "QuickRatio", "DividendYield", "FreeCashFlow", "CirculatingSupply", "TotalSupply", "MaxSupply", "InflationRate", "Fdv", "ActiveAddresses", "TransactionVolume", "TransactionCount", "FeesGenerated", "Tvl", "HashRate", "StakingRatio", "NakamotoCoefficient", "OrderBookDepth", "DeveloperActivity", "UserGrowth", "Revenue", "PriceToFeesRatio", "BitcoinDominance", "FearGreedIndex", "InventoryLevels", "CostOfProduction", "AllInSustainingCost", "ReserveReplacementRatio", "ContangoBackwardation", "DollarIndexExposure", "InflationCorrelation", "OpecSpareCapacity", "ChineseDemandIndex", "WeatherIndex", });
    internal_static_financial_HistoryResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_financial_HistoryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_financial_HistoryResponse_descriptor,
        new java.lang.String[] { "Symbol", "History", });
    internal_static_financial_EmptyRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_financial_EmptyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_financial_EmptyRequest_descriptor,
        new java.lang.String[] { });
    internal_static_financial_SymbolsResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_financial_SymbolsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_financial_SymbolsResponse_descriptor,
        new java.lang.String[] { "Symbols", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
