// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: financial_data.proto

package com.finsight.proto;

/**
 * Protobuf type {@code financial.HistoryResponse}
 */
public final class HistoryResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:financial.HistoryResponse)
    HistoryResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HistoryResponse.newBuilder() to construct.
  private HistoryResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HistoryResponse() {
    symbol_ = "";
    history_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new HistoryResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.finsight.proto.FinancialDataProto.internal_static_financial_HistoryResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.finsight.proto.FinancialDataProto.internal_static_financial_HistoryResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.finsight.proto.HistoryResponse.class, com.finsight.proto.HistoryResponse.Builder.class);
  }

  public static final int SYMBOL_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object symbol_ = "";
  /**
   * <code>string symbol = 1;</code>
   * @return The symbol.
   */
  @java.lang.Override
  public java.lang.String getSymbol() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      symbol_ = s;
      return s;
    }
  }
  /**
   * <code>string symbol = 1;</code>
   * @return The bytes for symbol.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSymbolBytes() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      symbol_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HISTORY_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.finsight.proto.PricePoint> history_;
  /**
   * <code>repeated .financial.PricePoint history = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.finsight.proto.PricePoint> getHistoryList() {
    return history_;
  }
  /**
   * <code>repeated .financial.PricePoint history = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.finsight.proto.PricePointOrBuilder> 
      getHistoryOrBuilderList() {
    return history_;
  }
  /**
   * <code>repeated .financial.PricePoint history = 2;</code>
   */
  @java.lang.Override
  public int getHistoryCount() {
    return history_.size();
  }
  /**
   * <code>repeated .financial.PricePoint history = 2;</code>
   */
  @java.lang.Override
  public com.finsight.proto.PricePoint getHistory(int index) {
    return history_.get(index);
  }
  /**
   * <code>repeated .financial.PricePoint history = 2;</code>
   */
  @java.lang.Override
  public com.finsight.proto.PricePointOrBuilder getHistoryOrBuilder(
      int index) {
    return history_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(symbol_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, symbol_);
    }
    for (int i = 0; i < history_.size(); i++) {
      output.writeMessage(2, history_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(symbol_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, symbol_);
    }
    for (int i = 0; i < history_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, history_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.finsight.proto.HistoryResponse)) {
      return super.equals(obj);
    }
    com.finsight.proto.HistoryResponse other = (com.finsight.proto.HistoryResponse) obj;

    if (!getSymbol()
        .equals(other.getSymbol())) return false;
    if (!getHistoryList()
        .equals(other.getHistoryList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
    hash = (53 * hash) + getSymbol().hashCode();
    if (getHistoryCount() > 0) {
      hash = (37 * hash) + HISTORY_FIELD_NUMBER;
      hash = (53 * hash) + getHistoryList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.finsight.proto.HistoryResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.finsight.proto.HistoryResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.finsight.proto.HistoryResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.finsight.proto.HistoryResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.finsight.proto.HistoryResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.finsight.proto.HistoryResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.finsight.proto.HistoryResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.finsight.proto.HistoryResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.finsight.proto.HistoryResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.finsight.proto.HistoryResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.finsight.proto.HistoryResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.finsight.proto.HistoryResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.finsight.proto.HistoryResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code financial.HistoryResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:financial.HistoryResponse)
      com.finsight.proto.HistoryResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.finsight.proto.FinancialDataProto.internal_static_financial_HistoryResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.finsight.proto.FinancialDataProto.internal_static_financial_HistoryResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.finsight.proto.HistoryResponse.class, com.finsight.proto.HistoryResponse.Builder.class);
    }

    // Construct using com.finsight.proto.HistoryResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      symbol_ = "";
      if (historyBuilder_ == null) {
        history_ = java.util.Collections.emptyList();
      } else {
        history_ = null;
        historyBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.finsight.proto.FinancialDataProto.internal_static_financial_HistoryResponse_descriptor;
    }

    @java.lang.Override
    public com.finsight.proto.HistoryResponse getDefaultInstanceForType() {
      return com.finsight.proto.HistoryResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.finsight.proto.HistoryResponse build() {
      com.finsight.proto.HistoryResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.finsight.proto.HistoryResponse buildPartial() {
      com.finsight.proto.HistoryResponse result = new com.finsight.proto.HistoryResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.finsight.proto.HistoryResponse result) {
      if (historyBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          history_ = java.util.Collections.unmodifiableList(history_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.history_ = history_;
      } else {
        result.history_ = historyBuilder_.build();
      }
    }

    private void buildPartial0(com.finsight.proto.HistoryResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.symbol_ = symbol_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.finsight.proto.HistoryResponse) {
        return mergeFrom((com.finsight.proto.HistoryResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.finsight.proto.HistoryResponse other) {
      if (other == com.finsight.proto.HistoryResponse.getDefaultInstance()) return this;
      if (!other.getSymbol().isEmpty()) {
        symbol_ = other.symbol_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (historyBuilder_ == null) {
        if (!other.history_.isEmpty()) {
          if (history_.isEmpty()) {
            history_ = other.history_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureHistoryIsMutable();
            history_.addAll(other.history_);
          }
          onChanged();
        }
      } else {
        if (!other.history_.isEmpty()) {
          if (historyBuilder_.isEmpty()) {
            historyBuilder_.dispose();
            historyBuilder_ = null;
            history_ = other.history_;
            bitField0_ = (bitField0_ & ~0x00000002);
            historyBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getHistoryFieldBuilder() : null;
          } else {
            historyBuilder_.addAllMessages(other.history_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              symbol_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              com.finsight.proto.PricePoint m =
                  input.readMessage(
                      com.finsight.proto.PricePoint.parser(),
                      extensionRegistry);
              if (historyBuilder_ == null) {
                ensureHistoryIsMutable();
                history_.add(m);
              } else {
                historyBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object symbol_ = "";
    /**
     * <code>string symbol = 1;</code>
     * @return The symbol.
     */
    public java.lang.String getSymbol() {
      java.lang.Object ref = symbol_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        symbol_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string symbol = 1;</code>
     * @return The bytes for symbol.
     */
    public com.google.protobuf.ByteString
        getSymbolBytes() {
      java.lang.Object ref = symbol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        symbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string symbol = 1;</code>
     * @param value The symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbol(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      symbol_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string symbol = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSymbol() {
      symbol_ = getDefaultInstance().getSymbol();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string symbol = 1;</code>
     * @param value The bytes for symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      symbol_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.util.List<com.finsight.proto.PricePoint> history_ =
      java.util.Collections.emptyList();
    private void ensureHistoryIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        history_ = new java.util.ArrayList<com.finsight.proto.PricePoint>(history_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.finsight.proto.PricePoint, com.finsight.proto.PricePoint.Builder, com.finsight.proto.PricePointOrBuilder> historyBuilder_;

    /**
     * <code>repeated .financial.PricePoint history = 2;</code>
     */
    public java.util.List<com.finsight.proto.PricePoint> getHistoryList() {
      if (historyBuilder_ == null) {
        return java.util.Collections.unmodifiableList(history_);
      } else {
        return historyBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .financial.PricePoint history = 2;</code>
     */
    public int getHistoryCount() {
      if (historyBuilder_ == null) {
        return history_.size();
      } else {
        return historyBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .financial.PricePoint history = 2;</code>
     */
    public com.finsight.proto.PricePoint getHistory(int index) {
      if (historyBuilder_ == null) {
        return history_.get(index);
      } else {
        return historyBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .financial.PricePoint history = 2;</code>
     */
    public Builder setHistory(
        int index, com.finsight.proto.PricePoint value) {
      if (historyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHistoryIsMutable();
        history_.set(index, value);
        onChanged();
      } else {
        historyBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .financial.PricePoint history = 2;</code>
     */
    public Builder setHistory(
        int index, com.finsight.proto.PricePoint.Builder builderForValue) {
      if (historyBuilder_ == null) {
        ensureHistoryIsMutable();
        history_.set(index, builderForValue.build());
        onChanged();
      } else {
        historyBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .financial.PricePoint history = 2;</code>
     */
    public Builder addHistory(com.finsight.proto.PricePoint value) {
      if (historyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHistoryIsMutable();
        history_.add(value);
        onChanged();
      } else {
        historyBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .financial.PricePoint history = 2;</code>
     */
    public Builder addHistory(
        int index, com.finsight.proto.PricePoint value) {
      if (historyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHistoryIsMutable();
        history_.add(index, value);
        onChanged();
      } else {
        historyBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .financial.PricePoint history = 2;</code>
     */
    public Builder addHistory(
        com.finsight.proto.PricePoint.Builder builderForValue) {
      if (historyBuilder_ == null) {
        ensureHistoryIsMutable();
        history_.add(builderForValue.build());
        onChanged();
      } else {
        historyBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .financial.PricePoint history = 2;</code>
     */
    public Builder addHistory(
        int index, com.finsight.proto.PricePoint.Builder builderForValue) {
      if (historyBuilder_ == null) {
        ensureHistoryIsMutable();
        history_.add(index, builderForValue.build());
        onChanged();
      } else {
        historyBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .financial.PricePoint history = 2;</code>
     */
    public Builder addAllHistory(
        java.lang.Iterable<? extends com.finsight.proto.PricePoint> values) {
      if (historyBuilder_ == null) {
        ensureHistoryIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, history_);
        onChanged();
      } else {
        historyBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .financial.PricePoint history = 2;</code>
     */
    public Builder clearHistory() {
      if (historyBuilder_ == null) {
        history_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        historyBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .financial.PricePoint history = 2;</code>
     */
    public Builder removeHistory(int index) {
      if (historyBuilder_ == null) {
        ensureHistoryIsMutable();
        history_.remove(index);
        onChanged();
      } else {
        historyBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .financial.PricePoint history = 2;</code>
     */
    public com.finsight.proto.PricePoint.Builder getHistoryBuilder(
        int index) {
      return getHistoryFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .financial.PricePoint history = 2;</code>
     */
    public com.finsight.proto.PricePointOrBuilder getHistoryOrBuilder(
        int index) {
      if (historyBuilder_ == null) {
        return history_.get(index);  } else {
        return historyBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .financial.PricePoint history = 2;</code>
     */
    public java.util.List<? extends com.finsight.proto.PricePointOrBuilder> 
         getHistoryOrBuilderList() {
      if (historyBuilder_ != null) {
        return historyBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(history_);
      }
    }
    /**
     * <code>repeated .financial.PricePoint history = 2;</code>
     */
    public com.finsight.proto.PricePoint.Builder addHistoryBuilder() {
      return getHistoryFieldBuilder().addBuilder(
          com.finsight.proto.PricePoint.getDefaultInstance());
    }
    /**
     * <code>repeated .financial.PricePoint history = 2;</code>
     */
    public com.finsight.proto.PricePoint.Builder addHistoryBuilder(
        int index) {
      return getHistoryFieldBuilder().addBuilder(
          index, com.finsight.proto.PricePoint.getDefaultInstance());
    }
    /**
     * <code>repeated .financial.PricePoint history = 2;</code>
     */
    public java.util.List<com.finsight.proto.PricePoint.Builder> 
         getHistoryBuilderList() {
      return getHistoryFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.finsight.proto.PricePoint, com.finsight.proto.PricePoint.Builder, com.finsight.proto.PricePointOrBuilder> 
        getHistoryFieldBuilder() {
      if (historyBuilder_ == null) {
        historyBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.finsight.proto.PricePoint, com.finsight.proto.PricePoint.Builder, com.finsight.proto.PricePointOrBuilder>(
                history_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        history_ = null;
      }
      return historyBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:financial.HistoryResponse)
  }

  // @@protoc_insertion_point(class_scope:financial.HistoryResponse)
  private static final com.finsight.proto.HistoryResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.finsight.proto.HistoryResponse();
  }

  public static com.finsight.proto.HistoryResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HistoryResponse>
      PARSER = new com.google.protobuf.AbstractParser<HistoryResponse>() {
    @java.lang.Override
    public HistoryResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<HistoryResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HistoryResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.finsight.proto.HistoryResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

