// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: financial_data.proto

package com.finsight.proto;

public interface HistoryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:financial.HistoryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string symbol = 1;</code>
   * @return The symbol.
   */
  java.lang.String getSymbol();
  /**
   * <code>string symbol = 1;</code>
   * @return The bytes for symbol.
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>repeated .financial.PricePoint history = 2;</code>
   */
  java.util.List<com.finsight.proto.PricePoint> 
      getHistoryList();
  /**
   * <code>repeated .financial.PricePoint history = 2;</code>
   */
  com.finsight.proto.PricePoint getHistory(int index);
  /**
   * <code>repeated .financial.PricePoint history = 2;</code>
   */
  int getHistoryCount();
  /**
   * <code>repeated .financial.PricePoint history = 2;</code>
   */
  java.util.List<? extends com.finsight.proto.PricePointOrBuilder> 
      getHistoryOrBuilderList();
  /**
   * <code>repeated .financial.PricePoint history = 2;</code>
   */
  com.finsight.proto.PricePointOrBuilder getHistoryOrBuilder(
      int index);
}
