// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: financial_data.proto

package com.finsight.proto;

public interface HistoryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:financial.HistoryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string symbol = 1;</code>
   * @return The symbol.
   */
  java.lang.String getSymbol();
  /**
   * <code>string symbol = 1;</code>
   * @return The bytes for symbol.
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <pre>
   * Número de días atrás
   * </pre>
   *
   * <code>int32 days = 2;</code>
   * @return The days.
   */
  int getDays();
}
