// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: financial_data.proto

package com.finsight.proto;

public interface PricePointOrBuilder extends
    // @@protoc_insertion_point(interface_extends:financial.PricePoint)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double open = 1;</code>
   * @return The open.
   */
  double getOpen();

  /**
   * <code>double high = 2;</code>
   * @return The high.
   */
  double getHigh();

  /**
   * <code>double low = 3;</code>
   * @return The low.
   */
  double getLow();

  /**
   * <code>double close = 4;</code>
   * @return The close.
   */
  double getClose();

  /**
   * <code>double volume = 5;</code>
   * @return The volume.
   */
  double getVolume();

  /**
   * <code>string date = 6;</code>
   * @return The date.
   */
  java.lang.String getDate();
  /**
   * <code>string date = 6;</code>
   * @return The bytes for date.
   */
  com.google.protobuf.ByteString
      getDateBytes();

  /**
   * <code>double market_cap = 7;</code>
   * @return The marketCap.
   */
  double getMarketCap();

  /**
   * <code>double trailing_pe = 8;</code>
   * @return The trailingPe.
   */
  double getTrailingPe();

  /**
   * <code>double forward_pe = 9;</code>
   * @return The forwardPe.
   */
  double getForwardPe();

  /**
   * <code>double peg_ratio = 10;</code>
   * @return The pegRatio.
   */
  double getPegRatio();

  /**
   * <code>double price_to_book = 11;</code>
   * @return The priceToBook.
   */
  double getPriceToBook();

  /**
   * <code>double price_to_sales = 12;</code>
   * @return The priceToSales.
   */
  double getPriceToSales();

  /**
   * <code>double enterprise_to_ebitda = 13;</code>
   * @return The enterpriseToEbitda.
   */
  double getEnterpriseToEbitda();

  /**
   * <code>double profit_margins = 14;</code>
   * @return The profitMargins.
   */
  double getProfitMargins();

  /**
   * <code>double operating_margins = 15;</code>
   * @return The operatingMargins.
   */
  double getOperatingMargins();

  /**
   * <code>double return_on_equity = 16;</code>
   * @return The returnOnEquity.
   */
  double getReturnOnEquity();

  /**
   * <code>double return_on_assets = 17;</code>
   * @return The returnOnAssets.
   */
  double getReturnOnAssets();

  /**
   * <code>double debt_to_equity = 18;</code>
   * @return The debtToEquity.
   */
  double getDebtToEquity();

  /**
   * <code>double current_ratio = 19;</code>
   * @return The currentRatio.
   */
  double getCurrentRatio();

  /**
   * <code>double quick_ratio = 20;</code>
   * @return The quickRatio.
   */
  double getQuickRatio();

  /**
   * <code>double dividend_yield = 21;</code>
   * @return The dividendYield.
   */
  double getDividendYield();

  /**
   * <code>double free_cash_flow = 22;</code>
   * @return The freeCashFlow.
   */
  double getFreeCashFlow();

  /**
   * <code>double circulating_supply = 23;</code>
   * @return The circulatingSupply.
   */
  double getCirculatingSupply();

  /**
   * <code>double total_supply = 24;</code>
   * @return The totalSupply.
   */
  double getTotalSupply();

  /**
   * <code>double max_supply = 25;</code>
   * @return The maxSupply.
   */
  double getMaxSupply();

  /**
   * <code>double inflation_rate = 26;</code>
   * @return The inflationRate.
   */
  double getInflationRate();

  /**
   * <code>double fdv = 27;</code>
   * @return The fdv.
   */
  double getFdv();

  /**
   * <code>double active_addresses = 28;</code>
   * @return The activeAddresses.
   */
  double getActiveAddresses();

  /**
   * <code>double transaction_volume = 29;</code>
   * @return The transactionVolume.
   */
  double getTransactionVolume();

  /**
   * <code>double transaction_count = 30;</code>
   * @return The transactionCount.
   */
  double getTransactionCount();

  /**
   * <code>double fees_generated = 31;</code>
   * @return The feesGenerated.
   */
  double getFeesGenerated();

  /**
   * <code>double tvl = 32;</code>
   * @return The tvl.
   */
  double getTvl();

  /**
   * <code>double hash_rate = 33;</code>
   * @return The hashRate.
   */
  double getHashRate();

  /**
   * <code>double staking_ratio = 34;</code>
   * @return The stakingRatio.
   */
  double getStakingRatio();

  /**
   * <code>double nakamoto_coefficient = 35;</code>
   * @return The nakamotoCoefficient.
   */
  double getNakamotoCoefficient();

  /**
   * <code>double order_book_depth = 36;</code>
   * @return The orderBookDepth.
   */
  double getOrderBookDepth();

  /**
   * <code>double developer_activity = 37;</code>
   * @return The developerActivity.
   */
  double getDeveloperActivity();

  /**
   * <code>double user_growth = 38;</code>
   * @return The userGrowth.
   */
  double getUserGrowth();

  /**
   * <code>double revenue = 39;</code>
   * @return The revenue.
   */
  double getRevenue();

  /**
   * <code>double price_to_fees_ratio = 40;</code>
   * @return The priceToFeesRatio.
   */
  double getPriceToFeesRatio();

  /**
   * <code>double bitcoin_dominance = 41;</code>
   * @return The bitcoinDominance.
   */
  double getBitcoinDominance();

  /**
   * <code>double fear_greed_index = 42;</code>
   * @return The fearGreedIndex.
   */
  double getFearGreedIndex();

  /**
   * <code>double inventory_levels = 43;</code>
   * @return The inventoryLevels.
   */
  double getInventoryLevels();

  /**
   * <code>double cost_of_production = 44;</code>
   * @return The costOfProduction.
   */
  double getCostOfProduction();

  /**
   * <code>double all_in_sustaining_cost = 45;</code>
   * @return The allInSustainingCost.
   */
  double getAllInSustainingCost();

  /**
   * <code>double reserve_replacement_ratio = 46;</code>
   * @return The reserveReplacementRatio.
   */
  double getReserveReplacementRatio();

  /**
   * <code>double contango_backwardation = 47;</code>
   * @return The contangoBackwardation.
   */
  double getContangoBackwardation();

  /**
   * <code>double dollar_index_exposure = 48;</code>
   * @return The dollarIndexExposure.
   */
  double getDollarIndexExposure();

  /**
   * <code>double inflation_correlation = 49;</code>
   * @return The inflationCorrelation.
   */
  double getInflationCorrelation();

  /**
   * <code>double opec_spare_capacity = 50;</code>
   * @return The opecSpareCapacity.
   */
  double getOpecSpareCapacity();

  /**
   * <code>double chinese_demand_index = 51;</code>
   * @return The chineseDemandIndex.
   */
  double getChineseDemandIndex();

  /**
   * <code>double weather_index = 52;</code>
   * @return The weatherIndex.
   */
  double getWeatherIndex();
}
