// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: financial_data.proto

package com.finsight.proto;

public interface StockPriceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:financial.StockPriceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string symbol = 1;</code>
   * @return The symbol.
   */
  java.lang.String getSymbol();
  /**
   * <code>string symbol = 1;</code>
   * @return The bytes for symbol.
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>double price = 2;</code>
   * @return The price.
   */
  double getPrice();

  /**
   * <pre>
   * ISO 8601 string time
   * </pre>
   *
   * <code>string timestamp = 3;</code>
   * @return The timestamp.
   */
  java.lang.String getTimestamp();
  /**
   * <pre>
   * ISO 8601 string time
   * </pre>
   *
   * <code>string timestamp = 3;</code>
   * @return The bytes for timestamp.
   */
  com.google.protobuf.ByteString
      getTimestampBytes();
}
