export type FundamentalCategory = "STOCKS" | "CRYPTO" | "COMMODITIES";
export type FundamentalFormatter = "currency" | "number" | "percent";

export interface FundamentalMetricDefinition {
  id: string;
  label: string;
  description: string;
  section: string;
  formatter: FundamentalFormatter;
  categories: FundamentalCategory[];
}

export const FUNDAMENTAL_METRIC_CATALOG: FundamentalMetricDefinition[] = [
  {
    id: "volume",
    label: "Volumen",
    description: "Cantidad negociada en el ultimo tramo disponible. Ayuda a contextualizar conviccion y liquidez.",
    section: "Actividad",
    formatter: "number",
    categories: ["STOCKS", "CRYPTO", "COMMODITIES"],
  },
  {
    id: "marketCap",
    label: "Capitalizacion",
    description: "Valor total del activo en el mercado. Da una idea del tamano y del riesgo relativo.",
    section: "Actividad",
    formatter: "currency",
    categories: ["STOCKS", "CRYPTO", "COMMODITIES"],
  },
  {
    id: "revenue",
    label: "Revenue",
    description: "Ingresos generados por el negocio o protocolo cuando ese dato esta disponible.",
    section: "Actividad",
    formatter: "currency",
    categories: ["STOCKS", "CRYPTO", "COMMODITIES"],
  },
  {
    id: "trailingPe",
    label: "Trailing P/E",
    description: "Relacion precio-beneficio usando ganancias historicas. Mide cuanto se paga por beneficio actual.",
    section: "Valoracion",
    formatter: "number",
    categories: ["STOCKS"],
  },
  {
    id: "forwardPe",
    label: "Forward P/E",
    description: "Relacion precio-beneficio usando ganancias esperadas. Refleja expectativas futuras.",
    section: "Valoracion",
    formatter: "number",
    categories: ["STOCKS"],
  },
  {
    id: "pegRatio",
    label: "PEG Ratio",
    description: "Relacion entre P/E y crecimiento esperado. Sirve para balancear precio con expansion futura.",
    section: "Valoracion",
    formatter: "number",
    categories: ["STOCKS"],
  },
  {
    id: "priceToBook",
    label: "Price/Book",
    description: "Compara precio de mercado con valor contable. Es util en sectores intensivos en balance.",
    section: "Valoracion",
    formatter: "number",
    categories: ["STOCKS"],
  },
  {
    id: "priceToSales",
    label: "Price/Sales",
    description: "Compara precio de mercado con ventas. Ayuda cuando las ganancias aun son inestables.",
    section: "Valoracion",
    formatter: "number",
    categories: ["STOCKS"],
  },
  {
    id: "enterpriseToEbitda",
    label: "EV/EBITDA",
    description: "Relacion entre valor empresa y EBITDA. Permite comparar companias con distinta deuda.",
    section: "Valoracion",
    formatter: "number",
    categories: ["STOCKS"],
  },
  {
    id: "profitMargins",
    label: "Margen neto",
    description: "Porcentaje de beneficio final sobre ingresos. Resume eficiencia despues de todos los costos.",
    section: "Rentabilidad",
    formatter: "percent",
    categories: ["STOCKS"],
  },
  {
    id: "operatingMargins",
    label: "Margen operativo",
    description: "Rentabilidad del negocio antes de efectos financieros e impuestos.",
    section: "Rentabilidad",
    formatter: "percent",
    categories: ["STOCKS"],
  },
  {
    id: "returnOnEquity",
    label: "ROE",
    description: "Retorno generado sobre el patrimonio. Mide que tan bien se usa el capital de los accionistas.",
    section: "Rentabilidad",
    formatter: "percent",
    categories: ["STOCKS"],
  },
  {
    id: "returnOnAssets",
    label: "ROA",
    description: "Retorno sobre activos. Ayuda a ver la eficiencia general del negocio.",
    section: "Rentabilidad",
    formatter: "percent",
    categories: ["STOCKS"],
  },
  {
    id: "debtToEquity",
    label: "Debt/Equity",
    description: "Mide apalancamiento frente al patrimonio. Cuanto mas alto, mayor dependencia de deuda.",
    section: "Solidez",
    formatter: "number",
    categories: ["STOCKS"],
  },
  {
    id: "currentRatio",
    label: "Current Ratio",
    description: "Capacidad de cubrir obligaciones de corto plazo con activos corrientes.",
    section: "Solidez",
    formatter: "number",
    categories: ["STOCKS"],
  },
  {
    id: "quickRatio",
    label: "Quick Ratio",
    description: "Version mas exigente de liquidez al excluir inventarios u otros activos menos inmediatos.",
    section: "Solidez",
    formatter: "number",
    categories: ["STOCKS"],
  },
  {
    id: "dividendYield",
    label: "Dividend Yield",
    description: "Rendimiento anual del dividendo sobre el precio. Importa para estrategias de income.",
    section: "Retorno al accionista",
    formatter: "percent",
    categories: ["STOCKS"],
  },
  {
    id: "freeCashFlow",
    label: "Free Cash Flow",
    description: "Caja libre despues de inversiones operativas. Es clave para calidad de beneficios.",
    section: "Retorno al accionista",
    formatter: "currency",
    categories: ["STOCKS"],
  },
  {
    id: "fdv",
    label: "FDV",
    description: "Valoracion totalmente diluida considerando toda la oferta potencial del token.",
    section: "Tokenomics",
    formatter: "currency",
    categories: ["CRYPTO"],
  },
  {
    id: "circulatingSupply",
    label: "Circulating Supply",
    description: "Tokens actualmente en circulacion. Es la base real para la capitalizacion actual.",
    section: "Tokenomics",
    formatter: "number",
    categories: ["CRYPTO"],
  },
  {
    id: "totalSupply",
    label: "Total Supply",
    description: "Oferta emitida hasta el momento. Ayuda a evaluar dilucion potencial restante.",
    section: "Tokenomics",
    formatter: "number",
    categories: ["CRYPTO"],
  },
  {
    id: "maxSupply",
    label: "Max Supply",
    description: "Oferta maxima prevista por el protocolo si existe un limite conocido.",
    section: "Tokenomics",
    formatter: "number",
    categories: ["CRYPTO"],
  },
  {
    id: "inflationRate",
    label: "Inflation Rate",
    description: "Ritmo de expansion de oferta. Impacta presion vendedora y escasez.",
    section: "Tokenomics",
    formatter: "percent",
    categories: ["CRYPTO"],
  },
  {
    id: "activeAddresses",
    label: "Active Addresses",
    description: "Cantidad aproximada de direcciones activas. Sirve como proxy de uso real de red.",
    section: "On-chain",
    formatter: "number",
    categories: ["CRYPTO"],
  },
  {
    id: "transactionVolume",
    label: "Transaction Volume",
    description: "Valor transferido en la red durante el periodo. Refuerza lectura de actividad economica.",
    section: "On-chain",
    formatter: "currency",
    categories: ["CRYPTO"],
  },
  {
    id: "transactionCount",
    label: "Transaction Count",
    description: "Numero de transacciones registradas. Mide frecuencia de uso.",
    section: "On-chain",
    formatter: "number",
    categories: ["CRYPTO"],
  },
  {
    id: "feesGenerated",
    label: "Fees Generated",
    description: "Comisiones capturadas por la red o protocolo. Aporta senales de demanda pagada.",
    section: "On-chain",
    formatter: "currency",
    categories: ["CRYPTO"],
  },
  {
    id: "tvl",
    label: "TVL",
    description: "Valor total bloqueado. Muy usado para medir traccion en protocolos DeFi.",
    section: "On-chain",
    formatter: "currency",
    categories: ["CRYPTO"],
  },
  {
    id: "hashRate",
    label: "Hash Rate",
    description: "Poder computacional dedicado a la red. Refleja seguridad en cadenas PoW.",
    section: "Seguridad de red",
    formatter: "number",
    categories: ["CRYPTO"],
  },
  {
    id: "stakingRatio",
    label: "Staking Ratio",
    description: "Porcentaje de la oferta comprometida en staking. Mide alineacion y reduccion de liquidez.",
    section: "Seguridad de red",
    formatter: "percent",
    categories: ["CRYPTO"],
  },
  {
    id: "nakamotoCoefficient",
    label: "Nakamoto Coefficient",
    description: "Cantidad minima de actores necesarios para comprometer la red. Cuanto mas alto, mejor.",
    section: "Seguridad de red",
    formatter: "number",
    categories: ["CRYPTO"],
  },
  {
    id: "orderBookDepth",
    label: "Order Book Depth",
    description: "Liquidez disponible alrededor del precio. Importa para slippage y ejecucion.",
    section: "Mercado",
    formatter: "currency",
    categories: ["CRYPTO"],
  },
  {
    id: "developerActivity",
    label: "Developer Activity",
    description: "Senal de mantenimiento y construccion del ecosistema.",
    section: "Mercado",
    formatter: "number",
    categories: ["CRYPTO"],
  },
  {
    id: "userGrowth",
    label: "User Growth",
    description: "Crecimiento estimado de usuarios o actividad economica asociada al protocolo.",
    section: "Mercado",
    formatter: "percent",
    categories: ["CRYPTO"],
  },
  {
    id: "priceToFeesRatio",
    label: "Price/Fees Ratio",
    description: "Relacion entre valoracion y fees generadas. Ayuda a juzgar multiples de protocolos.",
    section: "Mercado",
    formatter: "number",
    categories: ["CRYPTO"],
  },
  {
    id: "bitcoinDominance",
    label: "BTC Dominance",
    description: "Peso relativo de Bitcoin dentro del mercado cripto. Es una referencia de rotacion sectorial.",
    section: "Mercado",
    formatter: "percent",
    categories: ["CRYPTO"],
  },
  {
    id: "fearGreedIndex",
    label: "Fear & Greed",
    description: "Indice sintetico de sentimiento. Sirve para contextualizar fases de euforia o estres.",
    section: "Mercado",
    formatter: "number",
    categories: ["CRYPTO"],
  },
  {
    id: "inventoryLevels",
    label: "Inventory Levels",
    description: "Existencias disponibles o inventarios del commodity. Afecta tension entre oferta y demanda.",
    section: "Oferta y demanda",
    formatter: "number",
    categories: ["COMMODITIES"],
  },
  {
    id: "costOfProduction",
    label: "Cost of Production",
    description: "Costo estimado de producir una unidad adicional. Sirve para evaluar pisos economicos.",
    section: "Oferta y demanda",
    formatter: "currency",
    categories: ["COMMODITIES"],
  },
  {
    id: "allInSustainingCost",
    label: "AISC",
    description: "Costo total de sostenimiento usado mucho en mineria para comparar eficiencia operativa.",
    section: "Oferta y demanda",
    formatter: "currency",
    categories: ["COMMODITIES"],
  },
  {
    id: "reserveReplacementRatio",
    label: "Reserve Replacement",
    description: "Capacidad para reponer reservas o inventarios explotables a lo largo del tiempo.",
    section: "Oferta y demanda",
    formatter: "percent",
    categories: ["COMMODITIES"],
  },
  {
    id: "contangoBackwardation",
    label: "Contango/Backwardation",
    description: "Senal de la curva de futuros. Ayuda a leer escasez inmediata o abundancia.",
    section: "Curva y macro",
    formatter: "number",
    categories: ["COMMODITIES"],
  },
  {
    id: "dollarIndexExposure",
    label: "Dollar Index Exposure",
    description: "Sensibilidad aproximada del commodity al movimiento del dolar.",
    section: "Curva y macro",
    formatter: "number",
    categories: ["COMMODITIES"],
  },
  {
    id: "inflationCorrelation",
    label: "Inflation Correlation",
    description: "Relacion estadistica estimada con ciclos de inflacion. Importa para coberturas macro.",
    section: "Curva y macro",
    formatter: "number",
    categories: ["COMMODITIES"],
  },
  {
    id: "opecSpareCapacity",
    label: "OPEC Spare Capacity",
    description: "Capacidad ociosa disponible del cartel. Relevante sobre todo en energia.",
    section: "Curva y macro",
    formatter: "number",
    categories: ["COMMODITIES"],
  },
  {
    id: "chineseDemandIndex",
    label: "Chinese Demand",
    description: "Proxy de demanda china, muy relevante para metales y energia.",
    section: "Curva y macro",
    formatter: "number",
    categories: ["COMMODITIES"],
  },
  {
    id: "weatherIndex",
    label: "Weather Index",
    description: "Impacto estimado del clima en produccion o consumo del commodity.",
    section: "Curva y macro",
    formatter: "number",
    categories: ["COMMODITIES"],
  },
];
