export type FundamentalCategory = "STOCKS" | "CRYPTO" | "COMMODITIES";
export type FundamentalFormatter = "currency" | "number" | "percent";

export interface FundamentalMetricDefinition {
  id: string;
  label: string;
  description: string;
  section: string;
  formatter: FundamentalFormatter;
  categories: FundamentalCategory[];
  examples?: string;
}

export const FUNDAMENTAL_METRIC_CATALOG: FundamentalMetricDefinition[] = [
  {
    id: "volume",
    label: "Volumen",
    description: "Cuantidad negociada. Ayuda a ver si hay conviccion real detras del movimiento.",
    section: "Actividad",
    formatter: "number",
    categories: ["STOCKS", "CRYPTO", "COMMODITIES"],
    examples: "Volumen alto cuando el precio sube = confirmacion fuerte. Volumen bajo en subida = señal debil. Comparar con promedio de dias anteriores.",
  },
  {
    id: "marketCap",
    label: "Capitalizacion",
    description: "Valor total del activo. Empresas grandes tienen capitalizacion alta.",
    section: "Actividad",
    formatter: "currency",
    categories: ["STOCKS", "CRYPTO", "COMMODITIES"],
    examples: "Acciones con market cap alto son empresas establecidas. En crypto, market cap alto indica proyecto consolidado. Ratio util para valoracion.",
  },
  {
    id: "revenue",
    label: "Revenue",
    description: "Ingresos de la empresa o protocolo.",
    section: "Actividad",
    formatter: "currency",
    categories: ["STOCKS", "CRYPTO", "COMMODITIES"],
    examples: "Ingresos crecientes cada trimestre = empresa saludable. En crypto, revenue viene de comisiones. Comparar crecimiento con competidores.",
  },
  {
    id: "trailingPe",
    label: "Trailing P/E",
    description: "Precio dividido por beneficios. Te dice cuanto pagas por cada dolar de ganancia.",
    section: "Valoracion",
    formatter: "number",
    categories: ["STOCKS"],
    examples: "P/E bajo = accion barata. P/E alto = accion cara o con mucha creencia en futuro. Comparar con otras empresas del mismo sector.",
  },
  {
    id: "forwardPe",
    label: "Forward P/E",
    description: "Precio dividido por ganancias esperadas. Muestra expectativas futuras.",
    section: "Valoracion",
    formatter: "number",
    categories: ["STOCKS"],
    examples: "Forward P/E mas bajo que Trailing P/E = mejora esperada. Si ambos son altos, la accion es cara. Alerta cuando baja mucho.",
  },
  {
    id: "pegRatio",
    label: "PEG Ratio",
    description: "Relacion P/E ajustado por crecimiento. Ayuda a valorar con crecimiento.",
    section: "Valoracion",
    formatter: "number",
    categories: ["STOCKS"],
    examples: "PEG < 1 = barato considerando crecimiento. PEG entre 1-2 = justo. Usar en empresas de tecnologia en crecimiento.",
  },
  {
    id: "priceToBook",
    label: "Price/Book",
    description: "Precio sobre valor contable. Util para empresas con mucho activo.",
    section: "Valoracion",
    formatter: "number",
    categories: ["STOCKS"],
    examples: "P/B < 1.5 = accion barata. P/B alto en empresas con pocos activos es normal. Bancos suelen tener P/B mas bajo.",
  },
  {
    id: "priceToSales",
    label: "Price/Sales",
    description: "Precio sobre ventas. Util cuando no hay ganancias aun.",
    section: "Valoracion",
    formatter: "number",
    categories: ["STOCKS"],
    examples: "P/S < 2 = empresa barata. P/S > 10 = valuation alto. Ideal para empresas en crecimiento sin beneficios aun.",
  },
  {
    id: "enterpriseToEbitda",
    label: "EV/EBITDA",
    description: "Valor empresa sobre ganancias antes de interes e impuestos.",
    section: "Valoracion",
    formatter: "number",
    categories: ["STOCKS"],
    examples: "EV/EBITDA < 8 = empresa barata. > 15 = cara. Bueno para comparar empresas con distinta estructura de deuda.",
  },
  {
    id: "profitMargins",
    label: "Margen neto",
    description: "Beneficio final sobre ingresos. Mide eficiencia total.",
    section: "Rentabilidad",
    formatter: "percent",
    categories: ["STOCKS"],
    examples: "Margen neto alto = empresa eficiente. Margen creciente = mejor operativa. Comparar con competidores del mismo sector.",
  },
  {
    id: "operatingMargins",
    label: "Margen operativo",
    description: "Beneficio operativo sobre ingresos. Antes de interes e impuestos.",
    section: "Rentabilidad",
    formatter: "percent",
    categories: ["STOCKS"],
    examples: "Margen operativo estable = negocio predecible. Margen creciente = mejor eficiencia operativa. Ideal > 15%.",
  },
  {
    id: "returnOnEquity",
    label: "ROE",
    description: "Retorno sobre el capital de los accionistas.",
    section: "Rentabilidad",
    formatter: "percent",
    categories: ["STOCKS"],
    examples: "ROE alto significa buen uso del capital. ROE > 15% + crecimiento = empresa fuerte. Alerta si baja mucho.",
  },
  {
    id: "returnOnAssets",
    label: "ROA",
    description: "Retorno sobre todos los activos de la empresa.",
    section: "Rentabilidad",
    formatter: "percent",
    categories: ["STOCKS"],
    examples: "ROA > 10% = eficiente con activos. Bancos: ROA > 1% es bueno. Combinar con ROE.",
  },
  {
    id: "debtToEquity",
    label: "Debt/Equity",
    description: "Cuanta deuda tiene vs capital propio.",
    section: "Solidez",
    formatter: "number",
    categories: ["STOCKS"],
    examples: "D/E bajo = menos riesgo de deuda. D/E muy alto = alerta financiera. Sectores como utilities toleran mas deuda.",
  },
  {
    id: "currentRatio",
    label: "Current Ratio",
    description: "Capacidad de pagar obligaciones corto plazo.",
    section: "Solidez",
    formatter: "number",
    categories: ["STOCKS"],
    examples: "Ratio > 1.5 = saludable. Ratio < 1 = dificultad para pagar deudas. Retail necesita mas liquidez que tech.",
  },
  {
    id: "quickRatio",
    label: "Quick Ratio",
    description: "Liquidez sin contar inventarios.",
    section: "Solidez",
    formatter: "number",
    categories: ["STOCKS"],
    examples: "Quick ratio > 1 = liquidez inmediata. Quick ratio bajo en retail es normal por inventarios. Tech debe tener > 1.",
  },
  {
    id: "dividendYield",
    label: "Dividend Yield",
    description: "Rendimiento de dividendos sobre el precio.",
    section: "Retorno al accionista",
    formatter: "percent",
    categories: ["STOCKS"],
    examples: "Yield > 3% = buena inversion para ingresos. Yield muy alto (>6%) verificar sostenibilidad. REITs tienen yield alto.",
  },
  {
    id: "freeCashFlow",
    label: "Free Cash Flow",
    description: "Caja generada despues de inversiones. Mide verdadera generacion de dinero.",
    section: "Retorno al accionista",
    formatter: "currency",
    categories: ["STOCKS"],
    examples: "FCF positivo y creciente = empresa saludable. FCF negativo persistente = alerta. Calcula FCF yield.",
  },
  {
    id: "fdv",
    label: "FDV",
    description: "Valoracion si todos los tokens fueran circulando.",
    section: "Tokenomics",
    formatter: "currency",
    categories: ["CRYPTO"],
    examples: "FDV mas market cap similares = casi todos tokens en circulacion. Alto FDV tokens nuevos = inflacion futura.",
  },
  {
    id: "circulatingSupply",
    label: "Circulating Supply",
    description: "Tokens disponibles en circulacion.",
    section: "Tokenomics",
    formatter: "number",
    categories: ["CRYPTO"],
    examples: "Alto circulating supply + FDV similar = transparente. Team tokens locked = escasez futura.",
  },
  {
    id: "totalSupply",
    label: "Total Supply",
    description: "Todos los tokens emitidos hasta ahora.",
    section: "Tokenomics",
    formatter: "number",
    categories: ["CRYPTO"],
    examples: "Total supply creciendo rapido = inflacion alta. Comparar con circulating supply para ver escasez.",
  },
  {
    id: "maxSupply",
    label: "Max Supply",
    description: "Maximo de tokens que existiran nunca.",
    section: "Tokenomics",
    formatter: "number",
    categories: ["CRYPTO"],
    examples: "Max supply limitado = escasez futura. Bitcoin 21M es ejemplo clasico. Sin limite requiere confianza.",
  },
  {
    id: "inflationRate",
    label: "Inflation Rate",
    description: "Tasa de emision de nuevos tokens.",
    section: "Tokenomics",
    formatter: "percent",
    categories: ["CRYPTO"],
    examples: "Inflacion baja (<5%) = tokens sostenibles. Alta inflacion = presion vendedora. Eth 2.0 reduction.",
  },
  {
    id: "activeAddresses",
    label: "Active Addresses",
    description: "Cuantas direcciones usan la red. Mide adopcion real.",
    section: "On-chain",
    formatter: "number",
    categories: ["CRYPTO"],
    examples: "Direcciones creciendo con precio = acumulacion. Bajando = disminucion de usuarios.",
  },
  {
    id: "transactionVolume",
    label: "Transaction Volume",
    description: "Valor de transacciones en la red.",
    section: "On-chain",
    formatter: "currency",
    categories: ["CRYPTO"],
    examples: "Volumen alto + fees altos = actividad real. Bull market = volumen creciente.",
  },
  {
    id: "transactionCount",
    label: "Transaction Count",
    description: "Numero de transacciones totales.",
    section: "On-chain",
    formatter: "number",
    categories: ["CRYPTO"],
    examples: "Transacciones altas = red muy usada. DeFi suele tener muchas transacciones.",
  },
  {
    id: "feesGenerated",
    label: "Fees Generated",
    description: "Comisiones que genera la red.",
    section: "On-chain",
    formatter: "currency",
    categories: ["CRYPTO"],
    examples: "Fees altos = demanda real. Usuarios pagan por usar la red. Eth fees altos en bull markets.",
  },
  {
    id: "tvl",
    label: "TVL",
    description: "Valor total bloqueado en protocolos DeFi.",
    section: "On-chain",
    formatter: "currency",
    categories: ["CRYPTO"],
    examples: "TVL alto + pocos hacks = protocol seguro. TVL creciente + token bajando = oportunidad.",
  },
  {
    id: "hashRate",
    label: "Hash Rate",
    description: "Poder de mineria en redes PoW.",
    section: "Seguridad de red",
    formatter: "number",
    categories: ["CRYPTO"],
    examples: "Hash rate alto = seguridad. Mineros confian en la red. Bajar hash rate = alerta.",
  },
  {
    id: "stakingRatio",
    label: "Staking Ratio",
    description: "Porcentaje de tokens en staking.",
    section: "Seguridad de red",
    formatter: "percent",
    categories: ["CRYPTO"],
    examples: "Staking alto (>50%) = seguridad pero menos liquidez. Yield neto = inflacion - staking.",
  },
  {
    id: "nakamotoCoefficient",
    label: "Nakamoto Coefficient",
    description: "Cuantos actores necesitan para controlar la red.",
    section: "Seguridad de red",
    formatter: "number",
    categories: ["CRYPTO"],
    examples: "NC alto (>5) = descentralizado. NC bajo (<3) = centralizacion alta.",
  },
  {
    id: "orderBookDepth",
    label: "Order Book Depth",
    description: "Liquidez disponible alrededor del precio.",
    section: "Mercado",
    formatter: "currency",
    categories: ["CRYPTO"],
    examples: "Profundo = buen slippage para grandes trades. Estrecho = posible volatilidad.",
  },
  {
    id: "developerActivity",
    label: "Developer Activity",
    description: "Actividad de desarrollo en GitHub.",
    section: "Mercado",
    formatter: "number",
    categories: ["CRYPTO"],
    examples: "Desarrollo alto + token barato = proyecto early. Muchos commits = mantenimiento activo.",
  },
  {
    id: "userGrowth",
    label: "User Growth",
    description: "Crecimiento de usuarios del protocolo.",
    section: "Mercado",
    formatter: "percent",
    categories: ["CRYPTO"],
    examples: "Crecimiento >20% mensual = adopcion alta. Retencion de usuarios importante.",
  },
  {
    id: "priceToFeesRatio",
    label: "Price/Fees Ratio",
    description: "Valoracion relativa a fees generadas.",
    section: "Mercado",
    formatter: "number",
    categories: ["CRYPTO"],
    examples: "Ratio bajo + fees crecientes = valor oculto. Comparar con empresas tradicionales.",
  },
  {
    id: "bitcoinDominance",
    label: "BTC Dominance",
    description: "Peso de Bitcoin en el mercado crypto.",
    section: "Mercado",
    formatter: "percent",
    categories: ["CRYPTO"],
    examples: "Dominance bajando = altseason (otros llevan el rally). Alta = refugio.",
  },
  {
    id: "fearGreedIndex",
    label: "Fear & Greed",
    description: "Indice de sentimiento del mercado crypto.",
    section: "Mercado",
    formatter: "number",
    categories: ["CRYPTO"],
    examples: "Fear bajo (<20) + precios bajos = compra. Greed alto (>80) = toma de ganancias.",
  },
  {
    id: "inventoryLevels",
    label: "Inventory Levels",
    description: "Existencias de commodities.",
    section: "Oferta y demanda",
    formatter: "number",
    categories: ["COMMODITIES"],
    examples: "Inventarios bajos + demanda alta = precios altos. EIA reports como referencia.",
  },
  {
    id: "costOfProduction",
    label: "Cost of Production",
    description: "Costo de producir una unidad.",
    section: "Oferta y demanda",
    formatter: "currency",
    categories: ["COMMODITIES"],
    examples: "Precio > costo de produccion = margen positivo. Mineras con costos altos en baja precio = alerta.",
  },
  {
    id: "allInSustainingCost",
    label: "AISC",
    description: "Costo total de sostenimiento en mineria.",
    section: "Oferta y demanda",
    formatter: "currency",
    categories: ["COMMODITIES"],
    examples: "AISC bajo en oro = minas eficientes. Comparar AISC vs precio para timing.",
  },
  {
    id: "reserveReplacementRatio",
    label: "Reserve Replacement",
    description: "Capacidad de reemplazar reservas.",
    section: "Oferta y demanda",
    formatter: "percent",
    categories: ["COMMODITIES"],
    examples: "Ratio > 100% = reservas sostenidas. Mineras con ratio bajo = agotamiento.",
  },
  {
    id: "contangoBackwardation",
    label: "Contango/Backwardation",
    description: "Forma de la curva de futuros.",
    section: "Curva y macro",
    formatter: "number",
    categories: ["COMMODITIES"],
    examples: "Backwardation = escasez inmediata (futuros baratos). Contango = abundancia futura.",
  },
  {
    id: "dollarIndexExposure",
    label: "Dollar Index Exposure",
    description: "Relacion con el indice del dolar.",
    section: "Curva y macro",
    formatter: "number",
    categories: ["COMMODITIES"],
    examples: "Commodities caen cuando dolar sube. Correlacion negativa tipica. Gold a veces es inverso.",
  },
  {
    id: "inflationCorrelation",
    label: "Inflation Correlation",
    description: "Relacion con la inflacion.",
    section: "Curva y macro",
    formatter: "number",
    categories: ["COMMODITIES"],
    examples: "Commodities suben con inflacion. Hedge natural contra CPI. Correlation > 0.5 bueno.",
  },
  {
    id: "opecSpareCapacity",
    label: "OPEC Spare Capacity",
    description: "Capacidad disponible del cartel OPEP.",
    section: "Curva y macro",
    formatter: "number",
    categories: ["COMMODITIES"],
    examples: "Capacidad baja = oil bullish (escasez). Decisiones OPEP+ afectan este numero.",
  },
  {
    id: "chineseDemandIndex",
    label: "Chinese Demand",
    description: "Demanda estimada de China.",
    section: "Curva y macro",
    formatter: "number",
    categories: ["COMMODITIES"],
    examples: "China compra mucho metales = base para impulsar precios. PMI manufactura como indicador.",
  },
  {
    id: "weatherIndex",
    label: "Weather Index",
    description: "Impacto del clima en agricommodities.",
    section: "Curva y macro",
    formatter: "number",
    categories: ["COMMODITIES"],
    examples: "Sequia para agricultura = precios altos. Invierno = mas demanda de gas natural.",
  },
];