export type FundamentalCategory = "STOCKS" | "CRYPTO" | "COMMODITIES";
export type FundamentalFormatter = "currency" | "number" | "percent";

export interface FundamentalMetricDefinition {
  id: string;
  label: string;
  description: string;
  section: string;
  formatter: FundamentalFormatter;
  categories: FundamentalCategory[];
  examples?: string;
}

export const FUNDAMENTAL_METRIC_CATALOG: FundamentalMetricDefinition[] = [
  {
    id: "volume",
    label: "Volumen",
    description: "Cantidad negociada en el ultimo tramo disponible. Ayuda a contextualizar conviccion y liquidez.",
    section: "Actividad",
    formatter: "number",
    categories: ["STOCKS", "CRYPTO", "COMMODITIES"],
    examples: "Volumen alto en rompimiento confirma la ruptura. Volumen decreciente en tendencia = debilidad. Usar promedio 30 dias como referencia.",
  },
  {
    id: "marketCap",
    label: "Capitalizacion",
    description: "Valor total del activo en el mercado. Da una idea del tamano y del riesgo relativo.",
    section: "Actividad",
    formatter: "currency",
    categories: ["STOCKS", "CRYPTO", "COMMODITIES"],
    examples: "Market cap > $10B = empresa grande. En crypto, >$1B = proyecto consolidado. Ratio market cap/ventas para valoracion.",
  },
  {
    id: "revenue",
    label: "Revenue",
    description: "Ingresos generados por el negocio o protocolo cuando ese dato esta disponible.",
    section: "Actividad",
    formatter: "currency",
    categories: ["STOCKS", "CRYPTO", "COMMODITIES"],
    examples: "Crecimiento de revenue trimestral > 10% = salud corporativa. Revenue en crypto = fees protocolares. YoY growth > 20% es fuerte.",
  },
  {
    id: "trailingPe",
    label: "Trailing P/E",
    description: "Relacion precio-beneficio usando ganancias historicas. Mide cuanto se paga por beneficio actual.",
    section: "Valoracion",
    formatter: "number",
    categories: ["STOCKS"],
    examples: "P/E < 15 = barato, > 30 = caro. Comparar con sector. P/E en caída + revenue creciendo = compra.",
  },
  {
    id: "forwardPe",
    label: "Forward P/E",
    description: "Relacion precio-beneficio usando ganancias esperadas. Refleja expectativas futuras.",
    section: "Valoracion",
    formatter: "number",
    categories: ["STOCKS"],
    examples: "Forward P/E < Trailing P/E = mejora esperada. Analyst estimates reliability. Reversion a la media.",
  },
  {
    id: "pegRatio",
    label: "PEG Ratio",
    description: "Relacion entre P/E y crecimiento esperado. Sirve para balancear precio con expansion futura.",
    section: "Valoracion",
    formatter: "number",
    categories: ["STOCKS"],
    examples: "PEG < 1 = barato con crecimiento. PEG > 2 = caro aun con growth. Usar en crecimiento tech.",
  },
  {
    id: "priceToBook",
    label: "Price/Book",
    description: "Compara precio de mercado con valor contable. Es util en sectores intensivos en balance.",
    section: "Valoracion",
    formatter: "number",
    categories: ["STOCKS"],
    examples: "P/B < 1.5 = barato sectorial. P/B > 4 = valoracion alta. Acciones de valor often < 1.5.",
  },
  {
    id: "priceToSales",
    label: "Price/Sales",
    description: "Compara precio de mercado con ventas. Ayuda cuando las ganancias aun son inestables.",
    section: "Valoracion",
    formatter: "number",
    categories: ["STOCKS"],
    examples: "P/S < 2 = barato con potencial. P/S > 10 = alta valoracion. Ideal para empresas sin ganancias.",
  },
  {
    id: "enterpriseToEbitda",
    label: "EV/EBITDA",
    description: "Relacion entre valor empresa y EBITDA. Permite comparar companias con distinta deuda.",
    section: "Valoracion",
    formatter: "number",
    categories: ["STOCKS"],
    examples: "EV/EBITDA < 8 = barato. > 15 = caro sectorial. Usar en adquisiciones empresariales.",
  },
  {
    id: "profitMargins",
    label: "Margen neto",
    description: "Porcentaje de beneficio final sobre ingresos. Resume eficiencia despues de todos los costos.",
    section: "Rentabilidad",
    formatter: "percent",
    categories: ["STOCKS"],
    examples: "Margen neto > 20% = alta eficiencia. Margen creciente = mejora operativa. Comparar con competidores.",
  },
  {
    id: "operatingMargins",
    label: "Margen operativo",
    description: "Rentabilidad del negocio antes de efectos financieros e impuestos.",
    section: "Rentabilidad",
    formatter: "percent",
    categories: ["STOCKS"],
    examples: "Margen operativo creciente = mejor antes de impuestos. Margen estable = negocio predecible. Ideal > 15%.",
  },
  {
    id: "returnOnEquity",
    label: "ROE",
    description: "Retorno generado sobre el patrimonio. Mide que tan bien se usa el capital de los accionistas.",
    section: "Rentabilidad",
    formatter: "percent",
    categories: ["STOCKS"],
    examples: "ROE > 15% = eficiente. ROE > 25% + P/E < 15 = valor oculto. ROE decreciente = alerta.",
  },
  {
    id: "returnOnAssets",
    label: "ROA",
    description: "Retorno sobre activos. Ayuda a ver la eficiencia general del negocio.",
    section: "Rentabilidad",
    formatter: "percent",
    categories: ["STOCKS"],
    examples: "ROA > 10% = eficiente con activos. Bancos: ROA > 1% es bueno. ROA creciente + ROE creciente = salud.",
  },
  {
    id: "debtToEquity",
    label: "Debt/Equity",
    description: "Mide apalancamiento frente al patrimonio. Cuanto mas alto, mayor dependencia de deuda.",
    section: "Solidez",
    formatter: "number",
    categories: ["STOCKS"],
    examples: "D/E < 0.5 = bajo apalancamiento. D/E > 2 = alto riesgo. Sector financials toleran mas deuda.",
  },
  {
    id: "currentRatio",
    label: "Current Ratio",
    description: "Capacidad de cubrir obligaciones de corto plazo con activos corrientes.",
    section: "Solidez",
    formatter: "number",
    categories: ["STOCKS"],
    examples: "Current ratio > 1.5 = salud liquidez. < 1 = alerta. Retail ideal > 1.5, tech puede ser menor.",
  },
  {
    id: "quickRatio",
    label: "Quick Ratio",
    description: "Version mas exigente de liquidez al excluir inventarios u otros activos menos inmediatos.",
    section: "Solidez",
    formatter: "number",
    categories: ["STOCKS"],
    examples: "Quick ratio > 1 = liquidez sin inventario. Quick ratio < 0.5 = potencial problema. Usar en acciones de crecimiento.",
  },
  {
    id: "dividendYield",
    label: "Dividend Yield",
    description: "Rendimiento anual del dividendo sobre el precio. Importa para estrategias de income.",
    section: "Retorno al accionista",
    formatter: "percent",
    categories: ["STOCKS"],
    examples: "Yield > 3% + crecimiento dividendos = income estable. Yield > 6% = verificar sostenibilidad. REITs often > 4%.",
  },
  {
    id: "freeCashFlow",
    label: "Free Cash Flow",
    description: "Caja libre despues de inversiones operativas. Es clave para calidad de beneficios.",
    section: "Retorno al accionista",
    formatter: "currency",
    categories: ["STOCKS"],
    examples: "FCF creciente + dividendos = compañia saludable. FCF negativo persistente = alerta. Usar FCF yield = FCF/market cap.",
  },
  {
    id: "fdv",
    label: "FDV",
    description: "Valoracion totalmente diluida considerando toda la oferta potencial del token.",
    section: "Tokenomics",
    formatter: "currency",
    categories: ["CRYPTO"],
    examples: "FDV vs Market Cap ratio. FDV/Price < 2 = tokens casi todos en circulacion. Para proyectos nuevos, FDV acaso > realidad.",
  },
  {
    id: "circulatingSupply",
    label: "Circulating Supply",
    description: "Tokens actualmente en circulacion. Es la base real para la capitalizacion actual.",
    section: "Tokenomics",
    formatter: "number",
    categories: ["CRYPTO"],
    examples: "Circulating supply alto + FDV similar = tokens transparente. Team/VC tokens locked = supply futuro controlado.",
  },
  {
    id: "totalSupply",
    label: "Total Supply",
    description: "Oferta emitida hasta el momento. Ayuda a evaluar dilucion potencial restante.",
    section: "Tokenomics",
    formatter: "number",
    categories: ["CRYPTO"],
    examples: "Total supply creciente rapido = inflacion alta. Comparar burn rate vs emision. Eth 2.0 reducira inflation.",
  },
  {
    id: "maxSupply",
    label: "Max Supply",
    description: "Oferta maxima prevista por el protocolo si existe un limite conocido.",
    section: "Tokenomics",
    formatter: "number",
    categories: ["CRYPTO"],
    examples: "Max supply limitado + alta demanda = escasez futura. Bitcoin 21M es el ejemplo clasico. Sin max supply requiere trust.",
  },
  {
    id: "inflationRate",
    label: "Inflation Rate",
    description: "Ritmo de expansion de oferta. Impacta presion vendedora y escasez.",
    section: "Tokenomics",
    formatter: "percent",
    categories: ["CRYPTO"],
    examples: "Inflation < 5% = sostenible. Inflation > 20% = high sell pressure. Eth 2.0 bajo < 5% con staking.",
  },
  {
    id: "activeAddresses",
    label: "Active Addresses",
    description: "Cantidad aproximada de direcciones activas. Sirve como proxy de uso real de red.",
    section: "On-chain",
    formatter: "number",
    categories: ["CRYPTO"],
    examples: "Active addresses creciendo + precio estable = acumulacion. Correlacion con revenue/on-chain metrics.",
  },
  {
    id: "transactionVolume",
    label: "Transaction Volume",
    description: "Valor transferido en la red durante el periodo. Refuerza lectura de actividad economica.",
    section: "On-chain",
    formatter: "currency",
    categories: ["CRYPTO"],
    examples: "Transaction volume alto + fees altos = actividad real. Usar promedio 30 dias como referencia. Bull markets = volumen creciente.",
  },
  {
    id: "transactionCount",
    label: "Transaction Count",
    description: "Numero de transacciones registradas. Mide frecuencia de uso.",
    section: "On-chain",
    formatter: "number",
    categories: ["CRYPTO"],
    examples: "Tx count alto = frecuencia de actividad. Combinar con active addresses para metric de engagement. Defi = tx counts altos.",
  },
  {
    id: "feesGenerated",
    label: "Fees Generated",
    description: "Comisiones capturadas por la red o protocolo. Aporta senales de demanda pagada.",
    section: "On-chain",
    formatter: "currency",
    categories: ["CRYPTO"],
    examples: "Fees altos + usuarios estables = valor real. Fees como % de revenue. Eth fees altos en bull markets.",
  },
  {
    id: "tvl",
    label: "TVL",
    description: "Valor total bloqueado. Muy usado para medir traccion en protocolos DeFi.",
    section: "On-chain",
    formatter: "currency",
    categories: ["CRYPTO"],
    examples: "TVL alto + hacks bajos = protocol seguro. TVL/market cap ratio para valoracion. TVL creciente + token bajando = oportunidad.",
  },
  {
    id: "hashRate",
    label: "Hash Rate",
    description: "Poder computacional dedicado a la red. Refleja seguridad en cadenas PoW.",
    section: "Seguridad de red",
    formatter: "number",
    categories: ["CRYPTO"],
    examples: "Hash rate alto = seguridad PoW. Hash rate creciente = mas mineros. Bajar hash rate = vulnerabilidad.",
  },
  {
    id: "stakingRatio",
    label: "Staking Ratio",
    description: "Porcentaje de la oferta comprometida en staking. Mide alineacion y reduccion de liquidez.",
    section: "Seguridad de red",
    formatter: "percent",
    categories: ["CRYPTO"],
    examples: "Staking > 50% = alta seguridad pero menor liquididad. Inflacion - staking ratio = yield neto. Busca ratio creciente.",
  },
  {
    id: "nakamotoCoefficient",
    label: "Nakamoto Coefficient",
    description: "Cantidad minima de actores necesarios para comprometer la red. Cuanto mas alto, mejor.",
    section: "Seguridad de red",
    formatter: "number",
    categories: ["CRYPTO"],
    examples: "NC > 5 = descentralizado. NC < 3 = centralizacion alta. Pools validadores para NC.",
  },
  {
    id: "orderBookDepth",
    label: "Order Book Depth",
    description: "Liquidez disponible alrededor del precio. Importa para slippage y ejecucion.",
    section: "Mercado",
    formatter: "currency",
    categories: ["CRYPTO"],
    examples: "Depth alto = slippage bajo en grandes trades. Depth disminuyendo = posible volatilidad. Ideal 5% slippage.",
  },
  {
    id: "developerActivity",
    label: "Developer Activity",
    description: "Senal de mantenimiento y construccion del ecosistema.",
    section: "Mercado",
    formatter: "number",
    categories: ["CRYPTO"],
    examples: "Developer activity alto + token barato = alpha early. GitHub commits como proxy. Merge activity en mainnet.",
  },
  {
    id: "userGrowth",
    label: "User Growth",
    description: "Crecimiento estimado de usuarios o actividad economica asociada al protocolo.",
    section: "Mercado",
    formatter: "percent",
    categories: ["CRYPTO"],
    examples: "User growth > 20% MoM = adopcion alta. Usuarios activos diarios como metric. Cohort retention rates.",
  },
  {
    id: "priceToFeesRatio",
    label: "Price/Fees Ratio",
    description: "Relacion entre valoracion y fees generadas. Ayuda a juzgar multiples de protocolos.",
    section: "Mercado",
    formatter: "number",
    categories: ["CRYPTO"],
    examples: "Price/Fees bajo + fees crecientes = valor oculto. Fee yield = fees/market cap. Comparar con multiples tradicionales.",
  },
  {
    id: "bitcoinDominance",
    label: "BTC Dominance",
    description: "Peso relativo de Bitcoin dentro del mercado cripto. Es una referencia de rotacion sectorial.",
    section: "Mercado",
    formatter: "percent",
    categories: ["CRYPTO"],
    examples: "BTC dominance bajando = altseason. Alta dominance = vuelo a refugio. Ideal para timing de etfs.",
  },
  {
    id: "fearGreedIndex",
    label: "Fear & Greed",
    description: "Indice sintetico de sentimiento. Sirve para contextualizar fases de euforia o estres.",
    section: "Mercado",
    formatter: "number",
    categories: ["CRYPTO"],
    examples: "Fear < 20 + precios oversold = compra. Greed > 80 = toma de ganancias. Divergencia con precios.",
  },
  {
    id: "inventoryLevels",
    label: "Inventory Levels",
    description: "Existencias disponibles o inventarios del commodity. Afecta tension entre oferta y demanda.",
    section: "Oferta y demanda",
    formatter: "number",
    categories: ["COMMODITIES"],
    examples: "Inventarios bajos + demanda alta = precios altos. EIA reports como referencia. Inventories en gas natural.",
  },
  {
    id: "costOfProduction",
    label: "Cost of Production",
    description: "Costo estimado de producir una unidad adicional. Sirve para evaluar pisos economicos.",
    section: "Oferta y demanda",
    formatter: "currency",
    categories: ["COMMODITIES"],
    examples: "Precio > cost of production = margen positiva. Pisos en oro: $1200/oz. Oil breakeven varia por campo.",
  },
  {
    id: "allInSustainingCost",
    label: "AISC",
    description: "Costo total de sostenimiento usado mucho en mineria para comparar eficiencia operativa.",
    section: "Oferta y demanda",
    formatter: "currency",
    categories: ["COMMODITIES"],
    examples: "AISC oro bajo = minas baratas. AISC vs precio oro para timing. Minas con AISC creciendo = costos altos.",
  },
  {
    id: "reserveReplacementRatio",
    label: "Reserve Replacement",
    description: "Capacidad para reponer reservas o inventarios explotables a lo largo del tiempo.",
    section: "Oferta y demanda",
    formatter: "percent",
    categories: ["COMMODITIES"],
    examples: "Ratio > 100% = reservas sostenidas. Mineras con ratio bajo = agotamiento. Petrolio: replacement ratio.",
  },
  {
    id: "contangoBackwardation",
    label: "Contango/Backwardation",
    description: "Senal de la curva de futuros. Ayuda a leer escasez inmediata o abundancia.",
    section: "Curva y macro",
    formatter: "number",
    categories: ["COMMODITIES"],
    examples: "Backwardation = escasez inmediata. Contango = abundancia futura. Ideal backwardation profundo para compras.",
  },
  {
    id: "dollarIndexExposure",
    label: "Dollar Index Exposure",
    description: "Sensibilidad aproximada del commodity al movimiento del dolar.",
    section: "Curva y macro",
    formatter: "number",
    categories: ["COMMODITIES"],
    examples: "Commodities con alta exposicion DXY bajan con dolar fuerte. Oil suele tener correlacion negativa. Gold a veces positiva.",
  },
  {
    id: "inflationCorrelation",
    label: "Inflation Correlation",
    description: "Relacion estadistica estimada con ciclos de inflacion. Importa para coberturas macro.",
    section: "Curva y macro",
    formatter: "number",
    categories: ["COMMODITIES"],
    examples: "Commodities como hedge inflation. Correlation > 0.5 para cobertura. TIPS vs commodities correlacion.",
  },
  {
    id: "opecSpareCapacity",
    label: "OPEC Spare Capacity",
    description: "Capacidad ociosa disponible del cartel. Relevante sobre todo en energia.",
    section: "Curva y macro",
    formatter: "number",
    categories: ["COMMODITIES"],
    examples: "Spare capacity bajo = oil bullish. OPEC+ production decisions. Iran/Iraq capacity offline.",
  },
  {
    id: "chineseDemandIndex",
    label: "Chinese Demand",
    description: "Proxy de demanda china, muy relevante para metales y energia.",
    section: "Curva y macro",
    formatter: "number",
    categories: ["COMMODITIES"],
    examples: "Demanda china creciente = base metales bullish. Caixin PMI como proxy. Importaciones china como indicador.",
  },
  {
    id: "weatherIndex",
    label: "Weather Index",
    description: "Impacto estimado del clima en produccion o consumo del commodity.",
    section: "Curva y macro",
    formatter: "number",
    categories: ["COMMODITIES"],
    examples: "Weather index para agricultura: sequia = food bullish. Gas natural invierno = demanda alta. Usar NOAA forecasts.",
  },
];